using System.Text;

namespace IoT.Device.Generators;

internal static class ModelNameSyntaxGenerator
{
    public static string GenerateAugmentationClass(string className, string namespaceName, string model)
    {
        var sb = new StringBuilder();
        sb.Append("""
        //------------------------------------------------------------------------------
        // <auto-generated>
        //      This code was generated by a tool.
        //      
        """);
        sb.Append(ProductInfo.Product);
        sb.Append(" v");
        sb.Append(ProductInfo.Version);
        sb.Append(" (");
        sb.Append(ProductInfo.Copyright);
        sb.Append("""
        )
        //
        //      Changes to this file may cause incorrect behavior and will be lost
        //      if the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        namespace 
        """);
        sb.AppendLine(namespaceName);
        sb.Append("""
        {
            public partial class 
        """);
        sb.AppendLine(className);
        sb.Append("""
            {

        """);
        sb.Append("""
                public override string ModelName { get; } = "
        """);
        sb.Append(model);
        sb.Append("""
        ";
            }
        }
        """);

        return sb.ToString();
    }
}